trigger:
  - main

pool:
  vmImage: ubuntu-latest

variables:
  phpVersion: '8.3'

jobs:
  - deployment: VMDeploy
    displayName: Web deploy
    environment:
      name: 'laravel' # Name of the environment in Azure DevOps
      resourceType: VirtualMachine # Specifies that deployment will happen on a virtual machine
      resourceName: 'bishal' # Name of the Azure VM where deployment will occur
    strategy:
      runOnce:
        deploy:
          steps:
            - script: |
                sudo bash -c ' # Start of the deployment script
                cd /home/bishal/ # Change directory to the Laravel app directory
                ./laravel.sh
                '
              displayName: 'Continuous Integration and Deployment' # Display name for this deployment step
